databases:
  - name: lospuertoriquenos_DB
    plan: free
    databaseName: lospuertoriquenos_storage
    user: usuario

services:
  - type: web
    plan: free
    name: app_los_puertoriquenos_api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app_los_puertoriquenos_api.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lospuertoriquenos_storage
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4