# Generated by Django 5.0.7 on 2024-07-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntuaciones', '0002_rename_torneo_id_partida_torneo_jugada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugada',
            old_name='puntacion',
            new_name='puntuacion',
        ),
        migrations.AlterUniqueTogether(
            name='jugada',
            unique_together={('jugador', 'partida')},
        ),
    ]
